# Site
title: Đức Lê
bio: "Mình là một người thích sự tự do. Mình tin vào khả năng thay đổi bản thân và sự tích cực của mình để có thể lắng nghe và chia sẽ thông điệp về sự tự do và hạnh phúc đến mọi người."
description: "Đầy là blog cung cấp những kiến thức về phát triển bản thân và kinh nghiệm sống. Vì mục đích cuối cùng của chúng ta là được hạnh phúc."
reading_time: true
words_per_minute: 200
logo: "assets/img/logo.png"
background: "assets/img/placeholder-big.jpg"
tiled_bg: false # Set this true if you want to tile your background image, otherwise it will be covered
locale: en_US
url: https://kitokip.github.io

# Jekyll
permalink: /:title/
markdown: kramdown
highlighter: rouge
kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    enable_coderay: false
mathjax: true
sass:
    sass_dir: _sass
    style: compressed

# Comments
disqus_shortname: kitokip

# Social
# if you don't have any of social below, comment the line.
google:
    #plus:            #username
    analytics: ducqhle
    #verify:
    #ad-client:
    #ad-slot:
#bing-verify:
email: ducqhle@gmail.com
#twitter:           username
facebook: ducqhle
#github-url:         kitokip
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin: ducqhle
#xing:              username
instagram: ducqhle
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
youtube-channel: UCdfFqw442LrJMepasApN7XQ
#soundcloud: kitokip
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
    - jekyll-mentions
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude:
    [
        README.md,
        Gemfile,
        Gemfile.lock,
        node_modules,
        gulpfile.js,
        package.json,
        _site,
        src,
        vendor,
        CNAME,
        LICENSE,
        Rakefile,
    ]
