# Site
title: Đức Lê
bio: "Đọc blog này khi nghĩ mày không thể sống tốt hơn, mày éo muốn quan tâm và đang tìm cái gì đó 18+ nhưng tốt cho sức khoẻ."
description: "Đây là nơi mình viết những đạo lý dạy đời cho mấy thằng ml như mình đọc để ước mong một ngày được giác ngộ."
reading_time: true
words_per_minute: 200
logo: "assets/img/logo.jpg"
background: "assets/img/placeholder-big.jpg"
tiled_bg: false # Set this true if you want to tile your background image, otherwise it will be covered
locale: en_US
url: https://kitokip.github.io

# Jekyll
permalink: /:title/
markdown: kramdown
highlighter: rouge
kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    enable_coderay: false
mathjax: true
sass:
    sass_dir: _sass
    style: compressed

# Comments
disqus_shortname: kitokip

# Social
# if you don't have any of social below, comment the line.
google:
    #plus:            #username
    analytics: ducqhle
    #verify:
    #ad-client:
    #ad-slot:
#bing-verify:
#email: ducqhle@gmail.com
#twitter:           username
facebook: ducqhle
#github-url:         kitokip
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin: ducqhle
#xing:              username
instagram: ducqhle
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
youtube-channel: UCdfFqw442LrJMepasApN7XQ
#soundcloud: kitokip
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
    - jekyll-mentions
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude:
    [
        README.md,
        Gemfile,
        Gemfile.lock,
        node_modules,
        gulpfile.js,
        package.json,
        _site,
        src,
        vendor,
        CNAME,
        LICENSE,
        Rakefile,
    ]
